version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "2718:2718"
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_PORT=${DB_PORT}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
    restart: unless-stopped

  db:
    image: postgres:16
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      PGDATA: /var/lib/postgresql/data/pgdata
      POSTGRES_INITDB_WALDIR: ${POSTGRES_INITDB_WALDIR}
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - postgres_wal_data:/var/lib/postgresql/data/wal
    ports:
      - "${DB_PORT}:${DB_PORT}"
    restart: unless-stopped

volumes:
  postgres_data:
  postgres_wal_data:
